from __future__ import annotations

import copy
from typing import Any

from outlook_web import __version__ as APP_VERSION
from outlook_web.services.external_request_limits import (
    CALLER_ID_MAX_LEN,
    DETAIL_MAX_LEN,
    EMAIL_DOMAIN_MAX_LEN,
    PROJECT_KEY_MAX_LEN,
    REASON_MAX_LEN,
    TASK_ID_MAX_LEN,
    TASK_MAILBOX_PREFIX_MAX_LEN,
)
from outlook_web.services.mailbox_directory_contract import get_mailbox_catalog_contract
from outlook_web.services.provider_catalog import EXTERNAL_API_V1_PREFIX, get_external_api_capabilities_contract
from outlook_web.services.pool import VALID_RESULTS

from .builders import _json_value_schema, _nullable_string_enum_schema, _string_array_schema

def _schemas(capabilities: dict[str, Any]) -> dict[str, Any]:
    contract = get_mailbox_catalog_contract()
    endpoints = capabilities.get("endpoints") if isinstance(capabilities.get("endpoints"), dict) else {}
    mailbox_directory = capabilities.get("mailbox_directory") if isinstance(capabilities.get("mailbox_directory"), dict) else {}
    selection_policy = capabilities.get("selection_policy") if isinstance(capabilities.get("selection_policy"), dict) else {}
    selection_scopes = selection_policy.get("scopes") if isinstance(selection_policy.get("scopes"), dict) else {}
    pool_claim_scope = selection_scopes.get("explicit_pool_claim") if isinstance(selection_scopes.get("explicit_pool_claim"), dict) else {}
    task_temp_apply_scope = selection_scopes.get("task_temp_apply") if isinstance(selection_scopes.get("task_temp_apply"), dict) else {}
    integration_manifest = capabilities.get("integration_manifest") if isinstance(capabilities.get("integration_manifest"), dict) else {}
    pool = capabilities.get("pool") if isinstance(capabilities.get("pool"), dict) else {}
    task_temp_mailbox = capabilities.get("task_temp_mailbox") if isinstance(capabilities.get("task_temp_mailbox"), dict) else {}
    mailbox_session = capabilities.get("mailbox_session") if isinstance(capabilities.get("mailbox_session"), dict) else {}
    return {
        "ExternalEnvelope": {
            "type": "object",
            "required": ["success", "code", "message", "data"],
            "properties": {
                "success": {"type": "boolean"},
                "code": {"type": "string"},
                "message": {"type": "string"},
                "data": {},
            },
        },
        "HealthData": {
            "type": "object",
            "required": ["status", "service", "version", "server_time_utc", "database", "readiness"],
            "properties": {
                "status": {"type": "string"},
                "service": {"type": "string"},
                "version": {"type": "string"},
                "server_time_utc": {"type": "string"},
                "database": {"type": "string"},
                "upstream_probe_ok": {"type": ["boolean", "null"]},
                "last_probe_at": {"type": "string"},
                "last_probe_error": {"type": "string"},
                "readiness": {"$ref": "#/components/schemas/ExternalReadinessSummary"},
            },
        },
        "ExternalReadinessSummary": {
            "type": "object",
            "required": ["status", "database", "upstream_probe", "discovery", "providers", "mailbox_directory", "pool", "task_temp_mailbox", "warnings"],
            "properties": {
                "status": {"type": "string", "enum": ["ready", "degraded"]},
                "database": {"type": "string", "enum": ["ok", "error"]},
                "upstream_probe": {"type": "object", "additionalProperties": True},
                "discovery": {"type": "object", "additionalProperties": True},
                "providers": {"type": "object", "additionalProperties": True},
                "mailbox_directory": {"$ref": "#/components/schemas/ExternalReadinessMailboxDirectory"},
                "pool": {"type": "object", "additionalProperties": True},
                "task_temp_mailbox": {"type": "object", "additionalProperties": True},
                "warnings": _string_array_schema(),
            },
            "additionalProperties": True,
        },
        "ExternalReadinessMailboxDirectory": {
            "type": "object",
            "required": ["status", "endpoint", "scoped", "summary", "totals", "quick_probe_params"],
            "properties": {
                "status": {"type": "string", "enum": ["ready", "empty", "restricted", "degraded"]},
                "endpoint": {"type": "string", "example": f"{EXTERNAL_API_V1_PREFIX}/mailboxes"},
                "scoped": {"type": "boolean"},
                "summary": {"type": "object", "additionalProperties": {"type": "integer", "minimum": 0}},
                "totals": {"$ref": "#/components/schemas/ExternalReadinessMailboxDirectoryTotals"},
                "quick_probe_params": {"$ref": "#/components/schemas/ExternalReadinessMailboxDirectoryQuickProbe"},
                "warnings": _string_array_schema(),
            },
            "additionalProperties": True,
        },
        "ExternalReadinessMailboxDirectoryTotals": {
            "type": "object",
            "required": ["mailboxes", "account_mailboxes", "temp_mailboxes"],
            "properties": {
                "mailboxes": {"type": "integer", "minimum": 0},
                "account_mailboxes": {"type": "integer", "minimum": 0},
                "temp_mailboxes": {"type": "integer", "minimum": 0},
            },
            "additionalProperties": False,
        },
        "ExternalReadinessMailboxDirectoryQuickProbe": {
            "type": "object",
            "required": ["page", "page_size", "kind", "status", "read_capability", "action", "provider", "sort"],
            "properties": {
                "page": {"type": "integer", "minimum": 1, "example": 1},
                "page_size": {"type": "integer", "minimum": 1, "maximum": 200, "example": 1},
                "kind": {"type": "string", "enum": ["all"]},
                "status": {"type": "string", "enum": ["all"]},
                "read_capability": {"type": "string", "enum": ["all"]},
                "action": {"type": "string", "enum": ["all"]},
                "provider": {"type": "string", "enum": ["all"]},
                "sort": {"type": "string", "enum": ["updated_desc"]},
            },
            "additionalProperties": False,
        },
        "CapabilitiesData": {
            "type": "object",
            "required": [
                "service",
                "version",
                "public_mode",
                "features",
                "available_features",
                "restricted_features",
                "defaults",
                "deployment_env",
                "deployment_profile",
                "selection_policy",
                "provider_integration_guide",
                "integration_manifest",
                "integration_bundle",
                "quickstart",
                "documentation",
                "provider_filter",
                "provider_diagnostics",
                "endpoints",
                "mailbox_directory",
                "external_mailbox_read_contract",
                "mailbox_session",
                "pool",
                "task_temp_mailbox",
            ],
            "properties": {
                "service": {"type": "string", "example": "outlook-email-plus"},
                "version": {"type": "string"},
                "public_mode": {"type": "boolean"},
                "features": _string_array_schema(),
                "available_features": _string_array_schema(),
                "restricted_features": _string_array_schema(),
                "defaults": {"$ref": "#/components/schemas/ExternalCapabilitiesDefaults"},
                "deployment_env": {"type": "object", "additionalProperties": {"type": "string"}},
                "deployment_profile": {"$ref": "#/components/schemas/ProviderDeploymentProfile"},
                "selection_policy": {"$ref": "#/components/schemas/ProviderSelectionPolicy"},
                "provider_integration_guide": {"$ref": "#/components/schemas/ProviderIntegrationGuide"},
                "integration_manifest": {"$ref": "#/components/schemas/IntegrationManifest"},
                "integration_bundle": {"$ref": "#/components/schemas/IntegrationBundleDiscovery"},
                "quickstart": {"$ref": "#/components/schemas/IntegrationQuickstart"},
                "documentation": {"$ref": "#/components/schemas/ProviderDocumentation"},
                "provider_filter": {"type": "object", "additionalProperties": True},
                "provider_diagnostics": {"type": "object", "additionalProperties": True},
                "endpoints": {"$ref": "#/components/schemas/ExternalEndpointMap"},
                "mailbox_directory": {"$ref": "#/components/schemas/MailboxDirectoryDiscovery"},
                "external_mailbox_read_contract": {"type": "object", "additionalProperties": True},
                "mailbox_session": {"$ref": "#/components/schemas/MailboxSessionDiscovery"},
                "pool": {"$ref": "#/components/schemas/PoolDiscovery"},
                "task_temp_mailbox": {"$ref": "#/components/schemas/TaskTempMailboxDiscovery"},
            },
        },
        "ExternalCapabilitiesDefaults": {
            "type": "object",
            "required": [
                "pool_claim_provider",
                "pool_claim_provider_env",
                "temp_mail_provider",
                "temp_mail_provider_env",
                "active_mailbox_providers",
                "active_mailbox_provider_env",
            ],
            "properties": {
                "pool_claim_provider": {"type": "string"},
                "pool_claim_provider_env": {"type": "string"},
                "temp_mail_provider": {"type": "string"},
                "temp_mail_provider_env": {"type": "string"},
                "active_mailbox_providers": _string_array_schema(),
                "active_mailbox_provider_env": {"type": "string"},
            },
        },
        "IntegrationBundleDiscovery": {
            "type": "object",
            "required": ["endpoint", "response_contract"],
            "properties": {
                "endpoint": {"type": "string", "example": endpoints.get("integration_bundle") or f"{EXTERNAL_API_V1_PREFIX}/integration-bundle"},
                "response_contract": {"type": "string", "enum": ["integration_bundle"]},
                "recommended_for": _string_array_schema(),
            },
            "additionalProperties": True,
        },
        "ExternalEndpointMap": {
            "type": "object",
            "required": list(endpoints.keys()),
            "properties": {key: {"type": "string", "example": value} for key, value in endpoints.items()},
            "additionalProperties": {"type": "string"},
        },
        "ProviderDocumentation": {
            "type": "object",
            "required": ["version", "recommended_human_start", "recommended_machine_start", "entries"],
            "properties": {
                "version": {"type": "integer", "example": 1},
                "recommended_human_start": {"type": "string", "example": "provider_onboarding"},
                "recommended_machine_start": {"type": "string", "example": "openapi"},
                "entries": {
                    "type": "object",
                    "additionalProperties": {"$ref": "#/components/schemas/ProviderDocumentationEntry"},
                },
            },
            "additionalProperties": True,
        },
        "ProviderDocumentationEntry": {
            "type": "object",
            "required": ["label", "type", "purpose"],
            "properties": {
                "label": {"type": "string"},
                "type": {"type": "string", "enum": ["guide", "agent_prompt", "example", "api_contract", "api_docs"]},
                "path": {"type": "string"},
                "endpoint": {"type": "string"},
                "purpose": {"type": "string"},
            },
            "additionalProperties": True,
        },
        "ProviderSelectionPolicy": {
            "type": "object",
            "required": ["version", "source_priority", "config_file", "scopes", "templates", "selection_recipes", "selection_recipe_index"],
            "properties": {
                "version": {"type": "integer", "example": 1},
                "source_priority": _string_array_schema(selection_policy.get("source_priority") or []),
                "config_file": {"$ref": "#/components/schemas/ProviderSelectionConfigFile"},
                "scopes": {"type": "object", "additionalProperties": True},
                "templates": {"type": "object", "additionalProperties": True},
                "selection_recipes": {"type": "array", "items": {"$ref": "#/components/schemas/ProviderSelectionRecipe"}},
                "selection_recipe_index": {
                    "type": "object",
                    "additionalProperties": {"$ref": "#/components/schemas/ProviderSelectionRecipe"},
                },
            },
        },
        "ProviderDeploymentProfile": {
            "type": "object",
            "required": ["version", "env", "config_file", "templates", "provider_values", "aliases", "provider_examples", "selection_recipes", "selection_recipe_index"],
            "properties": {
                "version": {"type": "integer", "example": 1},
                "env": {"type": "object", "additionalProperties": {"type": "string"}},
                "config_file": {"$ref": "#/components/schemas/ProviderDeploymentConfigFile"},
                "templates": {"type": "object", "additionalProperties": True},
                "provider_values": {"type": "object", "additionalProperties": True},
                "config_env": {"type": "object", "additionalProperties": True},
                "config_settings": {"type": "object", "additionalProperties": True},
                "aliases": {"type": "object", "additionalProperties": True},
                "provider_examples": {"type": "object", "additionalProperties": {"type": "object", "additionalProperties": True}},
                "selection_recipes": {"type": "array", "items": {"$ref": "#/components/schemas/ProviderSelectionRecipe"}},
                "selection_recipe_index": {
                    "type": "object",
                    "additionalProperties": {"$ref": "#/components/schemas/ProviderSelectionRecipe"},
                },
            },
            "additionalProperties": True,
        },
        "ProviderSelectionConfigFile": {
            "type": "object",
            "required": [
                "enabled",
                "env",
                "formats",
                "path",
                "resolved_path",
                "loaded",
                "error_code",
                "error",
                "priority_slot",
                "diagnostic_source",
            ],
            "properties": {
                "enabled": {"type": "boolean"},
                "env": {"type": "string", "example": "OUTLOOK_EMAIL_PROVIDER_CONFIG_FILE"},
                "formats": _string_array_schema(["json", "toml"]),
                "path": {"type": "string"},
                "resolved_path": {"type": "string"},
                "loaded": {"type": "boolean"},
                "error_code": {"type": "string"},
                "error": {"type": "string"},
                "sections": _string_array_schema(["mailbox_providers", "providers", "mailbox", "env"]),
                "supported_sections": _string_array_schema(["mailbox_providers", "providers", "mailbox", "env"]),
                "priority": {"type": "string", "example": "after_env_before_settings"},
                "priority_slot": {"type": "string", "example": "provider_config_file"},
                "diagnostic_source": {"type": "string", "example": "config_file"},
            },
        },
        "ProviderDeploymentConfigFile": {
            "type": "object",
            "required": ["enabled", "env", "formats", "path", "resolved_path", "loaded", "error_code", "error"],
            "properties": {
                "enabled": {"type": "boolean"},
                "env": {"type": "string", "example": "OUTLOOK_EMAIL_PROVIDER_CONFIG_FILE"},
                "formats": _string_array_schema(["json", "toml"]),
                "path": {"type": "string"},
                "resolved_path": {"type": "string"},
                "loaded": {"type": "boolean"},
                "error_code": {"type": "string"},
                "error": {"type": "string"},
                "sections": _string_array_schema(["mailbox_providers", "providers", "mailbox", "env"]),
            },
            "additionalProperties": True,
        },
        "ProviderIntegrationGuide": {
            "type": "object",
            "required": [
                "version",
                "source_priority",
                "secret_policy",
                "documentation",
                "workflow",
                "aliases",
                "provider_filter",
                "endpoints",
                "providers",
                "selection_recipes",
                "selection_recipe_index",
            ],
            "properties": {
                "version": {"type": "integer", "example": 1},
                "source_priority": _string_array_schema(selection_policy.get("source_priority") or []),
                "generated_from": _string_array_schema(),
                "secret_policy": {"type": "object", "additionalProperties": True},
                "documentation": {"$ref": "#/components/schemas/ProviderDocumentation"},
                "workflow": {"type": "object", "additionalProperties": True},
                "aliases": {"type": "object", "additionalProperties": True},
                "provider_values": {"type": "object", "additionalProperties": True},
                "provider_filter": {"type": "object", "additionalProperties": True},
                "endpoints": {"type": "object", "additionalProperties": {"type": "string"}},
                "providers": {"type": "array", "items": {"$ref": "#/components/schemas/ProviderIntegrationGuideProvider"}},
                "selection_recipes": {"type": "array", "items": {"$ref": "#/components/schemas/ProviderSelectionRecipe"}},
                "selection_recipe_index": {
                    "type": "object",
                    "additionalProperties": {"$ref": "#/components/schemas/ProviderSelectionRecipe"},
                },
            },
            "additionalProperties": True,
        },
        "ProviderIntegrationGuideProvider": {
            "type": "object",
            "required": [
                "provider",
                "label",
                "kind",
                "active",
                "configured",
                "readiness_status",
                "readiness_reason",
                "required_env",
                "optional_env",
                "required_settings",
                "settings_keys",
                "secret_env",
                "secret_settings",
                "activation",
                "pool_claim_default",
                "pool_claim_request",
                "mailbox_directory_filter",
                "health",
                "endpoints",
                "aliases",
            ],
            "properties": {
                "provider": {"type": "string"},
                "label": {"type": "string"},
                "kind": {"type": "string", "enum": ["account", "temp"]},
                "active": {"type": "boolean"},
                "configured": {"type": "boolean"},
                "readiness_status": {"type": "string", "enum": ["ready", "needs_config", "inactive"]},
                "readiness_reason": {"type": "string"},
                "missing_config": _string_array_schema(),
                "required_env": _string_array_schema(),
                "optional_env": _string_array_schema(),
                "required_settings": _string_array_schema(),
                "settings_keys": _string_array_schema(),
                "secret_env": _string_array_schema(),
                "secret_settings": _string_array_schema(),
                "configuration": {"type": "object", "additionalProperties": True},
                "activation": {"type": "object", "additionalProperties": True},
                "runtime_default": {"type": "object", "additionalProperties": True},
                "pool_claim_default": {"type": "object", "additionalProperties": True},
                "pool_claim_request": {"type": "object", "additionalProperties": True},
                "task_temp_apply_request": {"type": "object", "additionalProperties": True},
                "mailbox_directory_filter": {"type": "object", "additionalProperties": True},
                "health": {"type": "object", "additionalProperties": True},
                "endpoints": {"type": "object", "additionalProperties": {"type": "string"}},
                "aliases": {"type": "object", "additionalProperties": True},
                "capabilities": {"type": "object", "additionalProperties": True},
                "selection_policy_scopes": {"type": "object", "additionalProperties": True},
                "account_type": {"type": "string"},
                "config_source": {"type": "string"},
            },
            "additionalProperties": True,
        },
        "ProviderSelectionRecipe": {
            "type": "object",
            "required": ["key", "scope", "provider", "label", "kind", "active", "source_priority", "provider_env", "description"],
            "properties": {
                "key": {"type": "string", "example": "explicit_pool_claim:duckmail"},
                "scope": {
                    "type": "string",
                    "enum": ["active_allowlist", "temp_runtime_default", "pool_claim_default", "explicit_pool_claim", "task_temp_apply"],
                },
                "provider": {"type": "string"},
                "label": {"type": "string"},
                "kind": {"type": "string"},
                "active": {"type": "boolean"},
                "source_priority": _string_array_schema(selection_policy.get("source_priority") or []),
                "provider_env": {"type": "array", "items": {"$ref": "#/components/schemas/IntegrationManifestKeyHint"}},
                "description": {"type": "string"},
                "configuration": {"$ref": "#/components/schemas/ProviderSelectionRecipeConfig"},
                "endpoint": {"type": "string"},
                "request": {"$ref": "#/components/schemas/ProviderSelectionRecipeRequest"},
            },
            "additionalProperties": True,
        },
        "ProviderSelectionRecipeConfig": {
            "type": "object",
            "properties": {
                "env": {"type": "object", "additionalProperties": _json_value_schema()},
                "provider_config": {"$ref": "#/components/schemas/ProviderSelectionRecipeProviderConfig"},
                "settings": {"type": "object", "additionalProperties": _json_value_schema()},
            },
            "additionalProperties": True,
        },
        "ProviderSelectionRecipeProviderConfig": {
            "type": "object",
            "required": ["object", "json", "toml"],
            "properties": {
                "object": {"type": "object", "additionalProperties": True},
                "json": {"type": "string"},
                "toml": {"type": "string"},
            },
            "additionalProperties": True,
        },
        "ProviderSelectionRecipeRequest": {
            "type": "object",
            "properties": {
                "method": {"type": "string", "enum": ["GET", "POST", "PUT", "PATCH", "DELETE"]},
                "field": {"type": "string"},
                "value": _json_value_schema(),
                "body": {"type": "object", "additionalProperties": _json_value_schema()},
                "required_body_fields": _string_array_schema(),
            },
            "additionalProperties": True,
        },
        "IntegrationManifest": {
            "type": "object",
            "required": [
                "version",
                "auth",
                "discovery",
                "selection",
                "deployment",
                "documentation",
                "quickstart",
                "secret_policy",
                "workflows",
                "providers",
                "selection_recipes",
                "selection_recipe_index",
            ],
            "properties": {
                "version": {"type": "integer", "example": integration_manifest.get("version") or 1},
                "auth": {"$ref": "#/components/schemas/IntegrationManifestAuth"},
                "discovery": {"$ref": "#/components/schemas/IntegrationManifestDiscovery"},
                "selection": {"$ref": "#/components/schemas/IntegrationManifestSelection"},
                "deployment": {"$ref": "#/components/schemas/IntegrationManifestDeployment"},
                "documentation": {"$ref": "#/components/schemas/ProviderDocumentation"},
                "quickstart": {"$ref": "#/components/schemas/IntegrationQuickstart"},
                "provider_filter": {"type": "object", "additionalProperties": True},
                "provider_diagnostics_summary": {"type": "object", "additionalProperties": True},
                "secret_policy": {"type": "object", "additionalProperties": True},
                "workflows": {"type": "array", "items": {"$ref": "#/components/schemas/IntegrationManifestWorkflow"}},
                "providers": {"type": "array", "items": {"$ref": "#/components/schemas/IntegrationManifestProvider"}},
                "selection_recipes": {"type": "array", "items": {"$ref": "#/components/schemas/ProviderSelectionRecipe"}},
                "selection_recipe_index": {
                    "type": "object",
                    "additionalProperties": {"$ref": "#/components/schemas/ProviderSelectionRecipe"},
                },
            },
            "additionalProperties": True,
        },
        "IntegrationManifestAuth": {
            "type": "object",
            "required": ["scheme", "header", "placeholder", "headers", "curl_header"],
            "properties": {
                "scheme": {"type": "string", "enum": ["api_key"]},
                "header": {"type": "string", "enum": ["X-API-Key"]},
                "placeholder": {"type": "string", "enum": ["<your-api-key>"]},
                "headers": {"type": "object", "additionalProperties": {"type": "string"}},
                "curl_header": {"type": "string", "example": "X-API-Key: <your-api-key>"},
            },
            "additionalProperties": True,
        },
        "IntegrationQuickstart": {
            "type": "object",
            "required": ["version", "auth", "recommended_sequence", "provider_selector_fields", "endpoints", "requests", "workflow_keys"],
            "properties": {
                "version": {"type": "integer", "example": 1},
                "auth": {"$ref": "#/components/schemas/IntegrationQuickstartAuth"},
                "recommended_sequence": {
                    "type": "array",
                    "items": {"$ref": "#/components/schemas/IntegrationQuickstartSequenceStep"},
                },
                "provider_selector_fields": {
                    "type": "object",
                    "additionalProperties": {"$ref": "#/components/schemas/IntegrationQuickstartProviderSelector"},
                },
                "endpoints": {"type": "object", "additionalProperties": {"type": "string"}},
                "requests": {
                    "type": "object",
                    "additionalProperties": {"$ref": "#/components/schemas/IntegrationQuickstartRequest"},
                },
                "workflow_keys": {"type": "object", "additionalProperties": {"type": "string"}},
            },
            "additionalProperties": True,
        },
        "IntegrationQuickstartAuth": {
            "type": "object",
            "required": ["scheme", "header", "placeholder", "headers", "curl_header"],
            "properties": {
                "scheme": {"type": "string", "enum": ["api_key"]},
                "header": {"type": "string", "enum": ["X-API-Key"]},
                "placeholder": {"type": "string", "enum": ["<your-api-key>"]},
                "headers": {"type": "object", "additionalProperties": {"type": "string"}},
                "curl_header": {"type": "string", "example": "X-API-Key: <your-api-key>"},
            },
            "additionalProperties": True,
        },
        "IntegrationQuickstartSequenceStep": {
            "type": "object",
            "required": ["step", "method", "endpoint"],
            "properties": {
                "step": {"type": "string"},
                "method": {"type": "string", "enum": ["GET", "POST", "PUT", "PATCH", "DELETE"]},
                "endpoint": {"type": "string"},
                "response_field": {"type": "string"},
                "query": {"type": "object", "additionalProperties": _json_value_schema()},
            },
            "additionalProperties": True,
        },
        "IntegrationQuickstartProviderSelector": {
            "type": "object",
            "required": ["field", "allowed_values", "optional", "source"],
            "properties": {
                "field": {"type": "string"},
                "allowed_values": _string_array_schema(),
                "optional": {"type": "boolean"},
                "source": {"type": "string"},
            },
            "additionalProperties": True,
        },
        "IntegrationQuickstartRequest": {
            "type": "object",
            "required": ["method", "endpoint"],
            "properties": {
                "method": {"type": "string", "enum": ["GET", "POST", "PUT", "PATCH", "DELETE"]},
                "endpoint": {"type": "string"},
                "query": {"type": "object", "additionalProperties": _json_value_schema()},
                "body": {"type": "object", "additionalProperties": _json_value_schema()},
            },
            "additionalProperties": True,
        },
        "IntegrationBundleData": {
            "type": "object",
            "required": [
                "version",
                "service",
                "app_version",
                "status",
                "generated_at",
                "auth",
                "endpoints",
                "legacy_endpoints",
                "compatibility",
                "documentation",
                "quickstart",
                "readiness",
                "provider_selection",
                "openapi",
                "workflows",
                "smoke_checks",
                "recommendations",
                "action_plan",
            ],
            "properties": {
                "version": {"type": "integer", "example": 1},
                "service": {"type": "string", "example": "outlook-email-plus"},
                "app_version": {"type": "string"},
                "status": {"type": "string", "enum": ["ready", "needs_config", "degraded"]},
                "generated_at": {"type": "string", "format": "date-time"},
                "auth": {"$ref": "#/components/schemas/IntegrationBundleAuth"},
                "endpoints": {"$ref": "#/components/schemas/ExternalEndpointMap"},
                "legacy_endpoints": {"type": "object", "additionalProperties": {"type": "string"}},
                "compatibility": {"type": "object", "additionalProperties": True},
                "documentation": {"$ref": "#/components/schemas/ProviderDocumentation"},
                "quickstart": {"$ref": "#/components/schemas/IntegrationQuickstart"},
                "readiness": {"$ref": "#/components/schemas/IntegrationBundleReadiness"},
                "provider_selection": {"$ref": "#/components/schemas/IntegrationBundleProviderSelection"},
                "openapi": {"$ref": "#/components/schemas/IntegrationBundleOpenApi"},
                "workflows": {"type": "array", "items": {"$ref": "#/components/schemas/IntegrationBundleWorkflow"}},
                "smoke_checks": {"type": "array", "items": {"$ref": "#/components/schemas/IntegrationBundleSmokeCheck"}},
                "recommendations": {"type": "array", "items": {"$ref": "#/components/schemas/IntegrationBundleRecommendation"}},
                "action_plan": {"$ref": "#/components/schemas/IntegrationBundleActionPlan"},
            },
            "additionalProperties": True,
        },
        "IntegrationBundleAuth": {
            "type": "object",
            "required": ["header", "placeholder"],
            "properties": {
                "header": {"type": "string", "enum": ["X-API-Key"]},
                "placeholder": {"type": "string", "enum": ["<your-api-key>"]},
            },
            "additionalProperties": False,
        },
        "IntegrationBundleReadiness": {
            "type": "object",
            "required": ["status", "external_api", "providers", "mailbox_directory", "pool", "task_temp_mailbox", "warnings"],
            "properties": {
                "status": {"type": "string", "enum": ["ready", "needs_config", "degraded"]},
                "external_api": {"$ref": "#/components/schemas/ExternalReadinessSummary"},
                "providers": {"$ref": "#/components/schemas/MailboxProviderReadinessSummary"},
                "mailbox_directory": {"$ref": "#/components/schemas/ExternalReadinessMailboxDirectory"},
                "pool": {"type": "object", "additionalProperties": True},
                "task_temp_mailbox": {"type": "object", "additionalProperties": True},
                "warnings": _string_array_schema(),
            },
            "additionalProperties": True,
        },
        "IntegrationBundleProviderSelection": {
            "type": "object",
            "required": ["source_priority", "selector_fields", "provider_values", "defaults", "config_file", "selection_recipes_count", "routing_matrix"],
            "properties": {
                "source_priority": _string_array_schema(),
                "selector_fields": {"type": "object", "additionalProperties": {"type": "string"}},
                "provider_values": {"type": "object", "additionalProperties": {"type": "array", "items": {"type": "string"}}},
                "defaults": {"type": "object", "additionalProperties": True},
                "config_file": {"type": "object", "additionalProperties": True},
                "selection_recipes_count": {"type": "integer", "minimum": 0},
                "routing_matrix": {"$ref": "#/components/schemas/MailboxProviderRoutingMatrix"},
            },
            "additionalProperties": True,
        },
        "IntegrationBundleOpenApi": {
            "type": "object",
            "required": ["endpoint", "version", "path_count", "schema_count", "operation_count"],
            "properties": {
                "endpoint": {"type": "string", "example": endpoints.get("openapi") or f"{EXTERNAL_API_V1_PREFIX}/openapi.json"},
                "version": {"type": "string", "example": "3.1.0"},
                "path_count": {"type": "integer", "minimum": 0},
                "schema_count": {"type": "integer", "minimum": 0},
                "operation_count": {"type": "integer", "minimum": 0},
            },
            "additionalProperties": False,
        },
        "IntegrationBundleWorkflow": {
            "type": "object",
            "required": ["key", "label", "description", "step_count"],
            "properties": {
                "key": {"type": "string"},
                "label": {"type": "string"},
                "description": {"type": "string"},
                "step_count": {"type": "integer", "minimum": 0},
            },
            "additionalProperties": False,
        },
        "IntegrationBundleSmokeCheck": {
            "type": "object",
            "required": ["key", "method", "endpoint", "purpose"],
            "properties": {
                "key": {"type": "string"},
                "method": {"type": "string", "enum": ["GET"]},
                "endpoint": {"type": "string"},
                "purpose": {"type": "string"},
            },
            "additionalProperties": False,
        },
        "IntegrationBundleRecommendation": {
            "type": "object",
            "required": ["key", "priority", "label", "endpoint"],
            "properties": {
                "key": {"type": "string"},
                "priority": {"type": "string", "enum": ["high", "medium", "low"]},
                "label": {"type": "string"},
                "endpoint": {"type": "string"},
            },
            "additionalProperties": True,
        },
        "IntegrationBundleActionPlan": {
            "type": "object",
            "required": ["version", "status", "summary", "items"],
            "properties": {
                "version": {"type": "integer", "example": 1},
                "status": {"type": "string", "enum": ["ready", "needs_config", "degraded"]},
                "summary": {"$ref": "#/components/schemas/IntegrationBundleActionPlanSummary"},
                "items": {"type": "array", "items": {"$ref": "#/components/schemas/IntegrationBundleActionItem"}},
            },
            "additionalProperties": False,
        },
        "IntegrationBundleActionPlanSummary": {
            "type": "object",
            "required": ["total", "blocking", "high", "medium", "low"],
            "properties": {
                "total": {"type": "integer", "minimum": 0},
                "blocking": {"type": "integer", "minimum": 0},
                "high": {"type": "integer", "minimum": 0},
                "medium": {"type": "integer", "minimum": 0},
                "low": {"type": "integer", "minimum": 0},
            },
            "additionalProperties": False,
        },
        "IntegrationBundleActionItem": {
            "type": "object",
            "required": ["key", "priority", "status", "blocking", "title", "detail"],
            "properties": {
                "key": {"type": "string"},
                "priority": {"type": "string", "enum": ["high", "medium", "low"]},
                "status": {"type": "string", "enum": ["ready", "action_required", "optional", "blocked"]},
                "blocking": {"type": "boolean"},
                "title": {"type": "string"},
                "detail": {"type": "string"},
                "endpoint": {"type": "string"},
                "command": {"type": "string"},
                "docs": {"type": "string"},
            },
            "additionalProperties": False,
        },
        "IntegrationManifestSelection": {
            "type": "object",
            "required": ["source_priority", "active_allowlist", "temp_runtime_default", "pool_claim_default", "task_temp_apply", "explicit_pool_claim", "aliases", "recipes", "recipe_index"],
            "properties": {
                "source_priority": _string_array_schema(selection_policy.get("source_priority") or []),
                "active_allowlist": {"type": "object", "additionalProperties": True},
                "temp_runtime_default": {"type": "object", "additionalProperties": True},
                "pool_claim_default": {"type": "object", "additionalProperties": True},
                "task_temp_apply": {"type": "object", "additionalProperties": True},
                "explicit_pool_claim": {"type": "object", "additionalProperties": True},
                "aliases": {"type": "object", "additionalProperties": True},
                "recipes": {"type": "array", "items": {"$ref": "#/components/schemas/ProviderSelectionRecipe"}},
                "recipe_index": {
                    "type": "object",
                    "additionalProperties": {"$ref": "#/components/schemas/ProviderSelectionRecipe"},
                },
            },
            "additionalProperties": True,
        },
        "IntegrationManifestDeployment": {
            "type": "object",
            "required": ["env", "config_file", "templates", "source_priority", "selection_recipes", "selection_recipe_index"],
            "properties": {
                "env": {"type": "object", "additionalProperties": {"type": "string"}},
                "config_file": {"$ref": "#/components/schemas/ProviderDeploymentConfigFile"},
                "templates": {"type": "object", "additionalProperties": True},
                "source_priority": _string_array_schema(selection_policy.get("source_priority") or []),
                "selection_recipes": {"type": "array", "items": {"$ref": "#/components/schemas/ProviderSelectionRecipe"}},
                "selection_recipe_index": {
                    "type": "object",
                    "additionalProperties": {"$ref": "#/components/schemas/ProviderSelectionRecipe"},
                },
            },
            "additionalProperties": True,
        },
        "IntegrationManifestDiscovery": {
            "type": "object",
            "required": ["recommended_sequence", "endpoints"],
            "properties": {
                "recommended_sequence": {"type": "array", "items": {"$ref": "#/components/schemas/IntegrationManifestDiscoveryStep"}},
                "endpoints": {"type": "object", "additionalProperties": {"type": "string"}},
            },
            "additionalProperties": True,
        },
        "IntegrationManifestDiscoveryStep": {
            "type": "object",
            "required": ["step", "method", "endpoint"],
            "properties": {
                "step": {"type": "string"},
                "method": {"type": "string", "enum": ["GET", "POST", "PUT", "PATCH", "DELETE"]},
                "endpoint": {"type": "string"},
                "response_field": {"type": "string"},
                "query": {"type": "object", "additionalProperties": True},
            },
            "additionalProperties": True,
        },
        "IntegrationManifestWorkflow": {
            "type": "object",
            "required": ["key", "label", "description", "steps"],
            "properties": {
                "key": {"type": "string"},
                "label": {"type": "string"},
                "description": {"type": "string"},
                "steps": {"type": "array", "items": {"$ref": "#/components/schemas/IntegrationManifestWorkflowStep"}},
            },
            "additionalProperties": True,
        },
        "IntegrationManifestWorkflowStep": {
            "type": "object",
            "required": ["key", "label", "description", "method", "endpoint", "auth"],
            "properties": {
                "key": {"type": "string"},
                "label": {"type": "string"},
                "description": {"type": "string"},
                "method": {"type": "string", "enum": ["GET", "POST", "PUT", "PATCH", "DELETE"]},
                "endpoint": {"type": "string"},
                "auth": {"type": "string", "enum": ["api_key"]},
                "request": {"type": "object", "additionalProperties": True},
                "response": {"type": "object", "additionalProperties": True},
                "next": {"type": "object", "additionalProperties": True},
            },
            "additionalProperties": True,
        },
        "IntegrationManifestProvider": {
            "type": "object",
            "required": [
                "provider",
                "label",
                "kind",
                "active",
                "configured",
                "readiness_status",
                "required_env",
                "optional_env",
                "settings_keys",
                "required_settings",
                "secret_env",
                "secret_settings",
                "env",
                "settings",
                "request_fields",
                "aliases",
                "capabilities",
                "endpoints",
                "health",
                "mailbox_directory_filter",
            ],
            "properties": {
                "provider": {"type": "string"},
                "label": {"type": "string"},
                "kind": {"type": "string"},
                "active": {"type": "boolean"},
                "configured": {"type": "boolean"},
                "readiness_status": {"type": "string"},
                "readiness_reason": {"type": "string"},
                "required_env": _string_array_schema(),
                "optional_env": _string_array_schema(),
                "settings_keys": _string_array_schema(),
                "required_settings": _string_array_schema(),
                "secret_env": _string_array_schema(),
                "secret_settings": _string_array_schema(),
                "env": {"type": "array", "items": {"$ref": "#/components/schemas/IntegrationManifestKeyHint"}},
                "settings": {"type": "array", "items": {"$ref": "#/components/schemas/IntegrationManifestKeyHint"}},
                "request_fields": {"type": "object", "additionalProperties": True},
                "config_file_examples": {"type": "object", "additionalProperties": True},
                "aliases": {"type": "object", "additionalProperties": True},
                "capabilities": {"type": "object", "additionalProperties": True},
                "endpoints": {"type": "object", "additionalProperties": {"type": "string"}},
                "health": {"type": "object", "additionalProperties": True},
                "mailbox_directory_filter": {"type": "object", "additionalProperties": True},
            },
            "additionalProperties": True,
        },
        "IntegrationManifestKeyHint": {
            "type": "object",
            "required": ["key", "required", "secret", "value"],
            "properties": {
                "key": {"type": "string"},
                "required": {"type": "boolean"},
                "secret": {"type": "boolean"},
                "value": {"type": ["string", "number", "boolean", "array", "object", "null"]},
                "default": {"type": ["string", "number", "boolean", "array", "object", "null"]},
            },
            "additionalProperties": True,
        },
        "MailboxDirectoryDiscovery": {
            "type": "object",
            "required": [
                "endpoint",
                "query_fields",
                "response_contract",
                "contract",
                "kind_definitions",
                "status_definitions",
                "read_capability_definitions",
                "action_definitions",
                "sort_definitions",
                "summary_fields",
                "quick_view_presets",
                "provider_context_field",
                "item_action_contract_field",
                "item_action_contract_source",
                "account_scope",
            ],
            "properties": {
                "endpoint": {"type": "string", "example": mailbox_directory.get("endpoint") or f"{EXTERNAL_API_V1_PREFIX}/mailboxes"},
                "query_fields": _string_array_schema(mailbox_directory.get("query_fields") or []),
                "response_contract": {"type": "string", "enum": ["unified_mailbox_directory"]},
                "contract": {"type": "object", "additionalProperties": True, "example": contract},
                "kind_definitions": {"type": "array", "items": {"type": "object", "additionalProperties": True}},
                "status_definitions": {"type": "array", "items": {"type": "object", "additionalProperties": True}},
                "read_capability_definitions": {"type": "array", "items": {"type": "object", "additionalProperties": True}},
                "action_definitions": {"type": "array", "items": {"type": "object", "additionalProperties": True}},
                "sort_definitions": {"type": "array", "items": {"type": "object", "additionalProperties": True}},
                "summary_fields": {"type": "array", "items": {"type": "object", "additionalProperties": True}},
                "quick_view_presets": {"type": "array", "items": {"$ref": "#/components/schemas/MailboxQuickViewPreset"}},
                "provider_context_field": {"type": "string", "enum": ["provider_context"]},
                "item_action_contract_field": {"type": "string", "enum": ["action_contract"]},
                "item_action_contract_source": {"type": "string"},
                "account_scope": {"type": "string"},
            },
        },
        "MailboxQuickViewPreset": {
            "type": "object",
            "required": ["key", "label", "label_en", "description", "description_en", "filters"],
            "properties": {
                "key": {"type": "string", "enum": [item["key"] for item in contract.get("quick_view_presets") or []]},
                "label": {"type": "string"},
                "label_en": {"type": "string"},
                "description": {"type": "string"},
                "description_en": {"type": "string"},
                "filters": {"$ref": "#/components/schemas/MailboxQuickViewPresetFilters"},
            },
            "additionalProperties": False,
        },
        "MailboxQuickViewPresetFilters": {
            "type": "object",
            "required": ["kind", "status", "read_capability", "action", "provider", "search", "sort"],
            "properties": {
                "kind": {"type": "string", "enum": list(contract["filters"]["kind"])},
                "status": {"type": "string", "enum": list(contract["filters"]["status"])},
                "read_capability": {"type": "string", "enum": list(contract["filters"]["read_capability"])},
                "action": {"type": "string", "enum": list(contract["filters"]["action"])},
                "provider": {"type": "string"},
                "search": {"type": "string"},
                "sort": {"type": "string", "enum": list(contract["filters"]["sort"])},
            },
            "additionalProperties": False,
        },
        "PoolDiscovery": {
            "type": "object",
            "required": [
                "external_enabled",
                "current_consumer_has_access",
                "requires_pool_access",
                "default_provider",
                "default_provider_env",
                "restrictions",
                "features",
                "claim_endpoint",
                "claim_fields",
                "release_endpoint",
                "release_fields",
                "complete_endpoint",
                "complete_fields",
                "stats_endpoint",
                "read_contract",
            ],
            "properties": {
                "external_enabled": {"type": "boolean"},
                "current_consumer_has_access": {"type": "boolean"},
                "requires_pool_access": {"type": "boolean"},
                "default_provider": {"type": "string"},
                "default_provider_env": {"type": "string"},
                "restrictions": _string_array_schema(),
                "features": _string_array_schema(),
                "claim_endpoint": {"type": "string", "example": pool.get("claim_endpoint") or f"{EXTERNAL_API_V1_PREFIX}/pool/claim-random"},
                "claim_fields": _string_array_schema(pool.get("claim_fields") or []),
                "release_endpoint": {"type": "string", "example": pool.get("release_endpoint") or f"{EXTERNAL_API_V1_PREFIX}/pool/claim-release"},
                "release_fields": _string_array_schema(pool.get("release_fields") or []),
                "complete_endpoint": {"type": "string", "example": pool.get("complete_endpoint") or f"{EXTERNAL_API_V1_PREFIX}/pool/claim-complete"},
                "complete_fields": _string_array_schema(pool.get("complete_fields") or []),
                "stats_endpoint": {"type": "string", "example": pool.get("stats_endpoint") or f"{EXTERNAL_API_V1_PREFIX}/pool/stats"},
                "read_contract": {"type": "object", "additionalProperties": True},
            },
        },
        "TaskTempMailboxDiscovery": {
            "type": "object",
            "required": ["apply_endpoint", "apply_fields", "finish_endpoint", "finish_fields", "read_contract"],
            "properties": {
                "apply_endpoint": {"type": "string", "example": task_temp_mailbox.get("apply_endpoint") or f"{EXTERNAL_API_V1_PREFIX}/temp-emails/apply"},
                "apply_fields": _string_array_schema(task_temp_mailbox.get("apply_fields") or []),
                "finish_endpoint": {"type": "string", "example": task_temp_mailbox.get("finish_endpoint") or f"{EXTERNAL_API_V1_PREFIX}/temp-emails/{{task_token}}/finish"},
                "finish_fields": _string_array_schema(task_temp_mailbox.get("finish_fields") or []),
                "read_contract": {"type": "object", "additionalProperties": True},
            },
        },
        "MailboxSessionDiscovery": {
            "type": "object",
            "required": ["start_endpoint", "read_endpoint", "close_endpoint", "start_fields", "read_fields", "close_fields", "read_action_values", "source_strategy_values", "read_contract"],
            "properties": {
                "start_endpoint": {"type": "string", "example": mailbox_session.get("start_endpoint") or f"{EXTERNAL_API_V1_PREFIX}/mailbox-sessions/start"},
                "read_endpoint": {"type": "string", "example": mailbox_session.get("read_endpoint") or f"{EXTERNAL_API_V1_PREFIX}/mailbox-sessions/read"},
                "close_endpoint": {"type": "string", "example": mailbox_session.get("close_endpoint") or f"{EXTERNAL_API_V1_PREFIX}/mailbox-sessions/close"},
                "start_fields": _string_array_schema(mailbox_session.get("start_fields") or []),
                "read_fields": _string_array_schema(mailbox_session.get("read_fields") or []),
                "close_fields": _string_array_schema(mailbox_session.get("close_fields") or []),
                "read_action_values": _string_array_schema(mailbox_session.get("read_action_values") or []),
                "source_strategy_values": _string_array_schema(mailbox_session.get("source_strategy_values") or []),
                "read_contract": {"type": "object", "additionalProperties": True},
            },
        },
        "ProviderCatalogData": {
            "type": "object",
            "required": ["mailbox_providers", "provider_diagnostics", "provider_filter", "deployment_profile", "selection_policy", "provider_integration_guide", "readiness_summary", "integration_manifest", "quickstart", "documentation"],
            "properties": {
                "mailbox_providers": {"type": "array", "items": {"type": "object", "additionalProperties": True}},
                "provider_diagnostics": {"type": "object", "additionalProperties": True},
                "provider_filter": {"type": "object", "additionalProperties": True},
                "deployment_env": {"type": "object", "additionalProperties": {"type": "string"}},
                "deployment_profile": {"$ref": "#/components/schemas/ProviderDeploymentProfile"},
                "selection_policy": {"$ref": "#/components/schemas/ProviderSelectionPolicy"},
                "provider_integration_guide": {"$ref": "#/components/schemas/ProviderIntegrationGuide"},
                "readiness_summary": {"$ref": "#/components/schemas/MailboxProviderReadinessSummary"},
                "integration_manifest": {"$ref": "#/components/schemas/IntegrationManifest"},
                "quickstart": {"$ref": "#/components/schemas/IntegrationQuickstart"},
                "documentation": {"$ref": "#/components/schemas/ProviderDocumentation"},
                "external_mailbox_read_contract": {"type": "object", "additionalProperties": True},
            },
            "additionalProperties": True,
        },
        "ProviderHealthData": {"type": "object", "additionalProperties": True},
        "ProviderPreflightData": {"type": "object", "additionalProperties": True},
        "UnifiedMailboxDirectory": {
            "type": "object",
            "required": ["success", "mailboxes", "summary", "facets", "pagination", "filters", "provider_context", "contract"],
            "properties": {
                "success": {"type": "boolean"},
                "mailboxes": {"type": "array", "items": {"$ref": "#/components/schemas/MailboxItem"}},
                "summary": {"type": "object", "additionalProperties": {"type": "integer"}},
                "facets": {"$ref": "#/components/schemas/MailboxFacets"},
                "pagination": {"$ref": "#/components/schemas/Pagination"},
                "filters": {"$ref": "#/components/schemas/MailboxFilters"},
                "provider_context": {"$ref": "#/components/schemas/MailboxProviderContext"},
                "contract": {"type": "object", "additionalProperties": True, "example": contract},
            },
        },
        "MailboxProviderContext": {
            "type": "object",
            "required": ["version", "defaults", "provider_filter", "provider_diagnostics", "documentation", "deployment_env", "deployment_profile", "selection_policy", "provider_integration_guide", "readiness_summary", "discovery"],
            "properties": {
                "version": {"type": "integer", "example": 1},
                "defaults": {"type": "object", "additionalProperties": True},
                "provider_filter": {"type": "object", "additionalProperties": True},
                "provider_diagnostics": {"type": "object", "additionalProperties": True},
                "documentation": {"$ref": "#/components/schemas/ProviderDocumentation"},
                "deployment_env": {"type": "object", "additionalProperties": {"type": "string"}},
                "deployment_profile": {"$ref": "#/components/schemas/ProviderDeploymentProfile"},
                "selection_policy": {"$ref": "#/components/schemas/ProviderSelectionPolicy"},
                "provider_integration_guide": {"$ref": "#/components/schemas/ProviderIntegrationGuide"},
                "readiness_summary": {"$ref": "#/components/schemas/MailboxProviderReadinessSummary"},
                "discovery": {"type": "object", "additionalProperties": True},
            },
        },
        "MailboxProviderReadinessSummary": {
            "type": "object",
            "required": ["version", "overall_status", "totals", "issues", "source_priority", "provider_selector_fields", "routing_matrix", "capability_matrix", "endpoints", "providers"],
            "properties": {
                "version": {"type": "integer", "example": 1},
                "overall_status": {"type": "string", "enum": ["ready", "needs_config", "degraded"]},
                "totals": {"type": "object", "additionalProperties": {"type": "integer", "minimum": 0}},
                "issues": {"type": "object", "additionalProperties": {"type": "integer", "minimum": 0}},
                "source_priority": {"type": "array", "items": {"type": "string"}},
                "provider_selector_fields": {
                    "type": "object",
                    "required": ["pool_claim", "task_temp_apply"],
                    "properties": {
                        "pool_claim": {"type": "string", "example": "provider"},
                        "task_temp_apply": {"type": "string", "example": "provider_name"},
                    },
                    "additionalProperties": True,
                },
                "routing_matrix": {"$ref": "#/components/schemas/MailboxProviderRoutingMatrix"},
                "capability_matrix": {"$ref": "#/components/schemas/MailboxProviderCapabilityMatrix"},
                "endpoints": {"type": "object", "additionalProperties": {"type": "string"}},
                "providers": {"type": "array", "items": {"$ref": "#/components/schemas/MailboxProviderReadinessProvider"}},
            },
            "additionalProperties": True,
        },
        "MailboxProviderCapabilityMatrix": {
            "type": "object",
            "required": ["version", "generated_from", "totals", "workflows", "providers"],
            "properties": {
                "version": {"type": "integer", "example": 1},
                "generated_from": {"type": "array", "items": {"type": "string"}},
                "totals": {"$ref": "#/components/schemas/MailboxProviderCapabilityTotals"},
                "workflows": {
                    "type": "object",
                    "additionalProperties": {"$ref": "#/components/schemas/MailboxProviderCapabilityWorkflow"},
                },
                "providers": {"type": "array", "items": {"$ref": "#/components/schemas/MailboxProviderCapabilityRow"}},
            },
            "additionalProperties": True,
        },
        "MailboxProviderCapabilityTotals": {
            "type": "object",
            "required": [
                "providers",
                "account_providers",
                "temp_providers",
                "dynamic_create_providers",
                "pool_inventory_providers",
                "task_temp_capable_providers",
                "pool_claim_capable_providers",
                "session_capable_providers",
                "needs_config_providers",
            ],
            "properties": {
                "providers": {"type": "integer", "minimum": 0},
                "account_providers": {"type": "integer", "minimum": 0},
                "temp_providers": {"type": "integer", "minimum": 0},
                "dynamic_create_providers": {"type": "integer", "minimum": 0},
                "pool_inventory_providers": {"type": "integer", "minimum": 0},
                "task_temp_capable_providers": {"type": "integer", "minimum": 0},
                "pool_claim_capable_providers": {"type": "integer", "minimum": 0},
                "session_capable_providers": {"type": "integer", "minimum": 0},
                "needs_config_providers": {"type": "integer", "minimum": 0},
            },
            "additionalProperties": True,
        },
        "MailboxProviderCapabilityWorkflow": {
            "type": "object",
            "required": ["workflow", "label", "provider_count", "providers", "selector_fields"],
            "properties": {
                "workflow": {"type": "string"},
                "label": {"type": "string"},
                "provider_count": {"type": "integer", "minimum": 0},
                "providers": {"type": "array", "items": {"type": "string"}},
                "selector_fields": {"type": "object", "additionalProperties": {"type": "string"}},
            },
            "additionalProperties": True,
        },
        "MailboxProviderCapabilityRow": {
            "type": "object",
            "required": [
                "kind",
                "provider",
                "label",
                "active",
                "configured",
                "readiness_status",
                "config_source",
                "aliases",
                "capabilities",
                "read",
                "lifecycle_actions",
                "workflow_support",
                "selection_fields",
                "configuration",
                "inventory",
                "endpoints",
            ],
            "properties": {
                "kind": {"type": "string", "enum": ["account", "temp"]},
                "provider": {"type": "string"},
                "label": {"type": "string"},
                "active": {"type": "boolean"},
                "configured": {"type": "boolean"},
                "readiness_status": {"type": "string"},
                "config_source": {"type": "string"},
                "aliases": {"type": "array", "items": {"type": "string"}},
                "capabilities": {"type": "object", "additionalProperties": {"type": "boolean"}},
                "read": {"$ref": "#/components/schemas/MailboxProviderCapabilityRead"},
                "lifecycle_actions": {"type": "array", "items": {"type": "string"}},
                "workflow_support": {"type": "object", "additionalProperties": {"type": "boolean"}},
                "selection_fields": {"type": "object", "additionalProperties": {"type": "object", "additionalProperties": True}},
                "configuration": {"type": "object", "additionalProperties": True},
                "inventory": {"type": "object", "additionalProperties": {"type": "integer", "minimum": 0}},
                "endpoints": {"type": "object", "additionalProperties": {"type": "string"}},
            },
            "additionalProperties": True,
        },
        "MailboxProviderCapabilityRead": {
            "type": "object",
            "required": ["capability", "capabilities", "actions"],
            "properties": {
                "capability": {"type": "string"},
                "capabilities": {"type": "array", "items": {"type": "string"}},
                "actions": {"type": "array", "items": {"type": "string"}},
            },
            "additionalProperties": True,
        },
        "MailboxProviderRoutingMatrix": {
            "type": "object",
            "required": ["version", "source_priority", "scopes"],
            "properties": {
                "version": {"type": "integer", "example": 1},
                "source_priority": {"type": "array", "items": {"type": "string"}},
                "scopes": {
                    "type": "object",
                    "additionalProperties": {"$ref": "#/components/schemas/MailboxProviderRoutingScope"},
                },
            },
            "additionalProperties": True,
        },
        "MailboxProviderRoutingScope": {
            "type": "object",
            "required": ["scope", "label", "request_field", "settings_key", "env", "endpoint", "allowed_values", "counts", "providers"],
            "properties": {
                "scope": {"type": "string"},
                "label": {"type": "string"},
                "request_field": {"type": "string"},
                "settings_key": {"type": "string"},
                "env": {"type": "string"},
                "endpoint": {"type": "string"},
                "allowed_values": {"type": "array", "items": {"type": "string"}},
                "counts": {"type": "object", "additionalProperties": {"type": "integer", "minimum": 0}},
                "providers": {"type": "array", "items": {"$ref": "#/components/schemas/MailboxProviderRoutingProvider"}},
            },
            "additionalProperties": True,
        },
        "MailboxProviderRoutingProvider": {
            "type": "object",
            "required": ["provider", "canonical_provider", "label", "kind", "active", "configured", "usable", "status", "reason", "aliases", "endpoints"],
            "properties": {
                "provider": {"type": "string"},
                "canonical_provider": {"type": "string"},
                "label": {"type": "string"},
                "kind": {"type": "string"},
                "active": {"type": "boolean"},
                "configured": {"type": "boolean"},
                "usable": {"type": "boolean"},
                "status": {"type": "string"},
                "reason": {"type": "string"},
                "aliases": {"type": "array", "items": {"type": "string"}},
                "endpoints": {"type": "object", "additionalProperties": {"type": "string"}},
            },
            "additionalProperties": True,
        },
        "MailboxProviderReadinessProvider": {
            "type": "object",
            "required": ["kind", "provider", "label", "active", "configured", "readiness_status", "mailbox_count", "account_count", "temp_count", "can_dynamic_create", "requires_pool_inventory", "read_capability", "missing_config_count", "endpoints"],
            "properties": {
                "kind": {"type": "string"},
                "provider": {"type": "string"},
                "label": {"type": "string"},
                "active": {"type": "boolean"},
                "configured": {"type": "boolean"},
                "readiness_status": {"type": "string"},
                "mailbox_count": {"type": "integer", "minimum": 0},
                "account_count": {"type": "integer", "minimum": 0},
                "temp_count": {"type": "integer", "minimum": 0},
                "can_dynamic_create": {"type": "boolean"},
                "requires_pool_inventory": {"type": "boolean"},
                "read_capability": {"type": "string"},
                "read_capabilities": {"type": "array", "items": {"type": "string"}},
                "missing_config_count": {"type": "integer", "minimum": 0},
                "endpoints": {"type": "object", "additionalProperties": {"type": "string"}},
            },
            "additionalProperties": True,
        },
        "MailboxFacets": {
            "type": "object",
            "required": ["kinds", "statuses", "read_capabilities", "providers", "actions"],
            "properties": {
                "kinds": {"type": "array", "items": {"$ref": "#/components/schemas/MailboxKindFacet"}},
                "statuses": {"type": "array", "items": {"$ref": "#/components/schemas/MailboxStatusFacet"}},
                "read_capabilities": {"type": "array", "items": {"$ref": "#/components/schemas/MailboxReadCapabilityFacet"}},
                "providers": {"type": "array", "items": {"$ref": "#/components/schemas/MailboxProviderFacet"}},
                "actions": {"type": "array", "items": {"$ref": "#/components/schemas/MailboxActionFacet"}},
            },
        },
        "MailboxFilters": {
            "type": "object",
            "required": ["kind", "status", "read_capability", "action", "provider", "search", "sort"],
            "properties": {
                "kind": {"type": "string", "enum": list(contract["filters"]["kind"])},
                "status": {"type": "string", "enum": list(contract["filters"]["status"])},
                "read_capability": {"type": "string", "enum": list(contract["filters"]["read_capability"])},
                "action": {"type": "string", "enum": list(contract["filters"]["action"])},
                "provider": {"type": "string"},
                "search": {"type": "string"},
                "sort": {"type": "string", "enum": list(contract["filters"]["sort"])},
            },
        },
        "MailboxKindFacet": {
            "type": "object",
            "required": ["kind", "label", "label_en", "summary_key", "count"],
            "properties": {
                "kind": {"type": "string", "enum": [item["kind"] for item in contract.get("kind_definitions") or []]},
                "label": {"type": "string"},
                "label_en": {"type": "string"},
                "summary_key": {"type": "string"},
                "count": {"type": "integer", "minimum": 0},
            },
        },
        "MailboxStatusFacet": {
            "type": "object",
            "required": ["status", "label", "label_en", "count"],
            "properties": {
                "status": {"type": "string", "enum": [item["status"] for item in contract.get("status_definitions") or []]},
                "label": {"type": "string"},
                "label_en": {"type": "string"},
                "count": {"type": "integer", "minimum": 0},
            },
        },
        "MailboxReadCapabilityFacet": {
            "type": "object",
            "required": ["read_capability", "label", "label_en", "count"],
            "properties": {
                "read_capability": {
                    "type": "string",
                    "enum": [item["read_capability"] for item in contract.get("read_capability_definitions") or []],
                },
                "label": {"type": "string"},
                "label_en": {"type": "string"},
                "count": {"type": "integer", "minimum": 0},
            },
        },
        "MailboxProviderFacet": {
            "type": "object",
            "required": ["provider", "label", "kind", "count"],
            "properties": {
                "provider": {"type": "string"},
                "label": {"type": "string"},
                "kind": {"type": "string"},
                "count": {"type": "integer", "minimum": 0},
            },
        },
        "MailboxActionFacet": {
            "type": "object",
            "required": ["action", "label", "label_en", "count"],
            "properties": {
                "action": {"type": "string", "enum": [item["action"] for item in contract.get("action_definitions") or []]},
                "label": {"type": "string"},
                "label_en": {"type": "string"},
                "count": {"type": "integer", "minimum": 0},
            },
        },
        "MailboxItem": {
            "type": "object",
            "required": [
                "id",
                "source_id",
                "kind",
                "email",
                "domain",
                "status",
                "provider",
                "provider_label",
                "read_capability",
                "actions",
                "action_contract",
                "meta",
            ],
            "properties": {
                "id": {"type": "string"},
                "source_id": {"type": "integer"},
                "kind": {"type": "string", "enum": list(contract.get("kinds") or [])},
                "email": {"type": "string"},
                "domain": {"type": "string"},
                "status": {"type": "string"},
                "pool_status": {"type": "string"},
                "source": {"type": "string"},
                "provider": {"type": "string"},
                "provider_label": {"type": "string"},
                "account_type": {"type": "string"},
                "read_capability": {"type": "string"},
                "group": {"type": "object", "additionalProperties": True},
                "labels": {"type": "array", "items": {"type": "string"}},
                "remark": {"type": "string"},
                "latest": {"type": "object", "additionalProperties": True},
                "timestamps": {"type": "object", "additionalProperties": True},
                "notification_enabled": {"type": "boolean"},
                "actions": {"type": "object", "additionalProperties": {"type": "boolean"}},
                "action_contract": {"$ref": "#/components/schemas/MailboxActionContract"},
                "meta": {"type": "object", "additionalProperties": True},
            },
        },
        "MailboxActionContract": {
            "type": "object",
            "required": ["version", "read_by", "read_capability", "external_read_contract", "external", "internal"],
            "properties": {
                "version": {"type": "integer", "example": 1},
                "read_by": {"type": "array", "items": {"type": "string"}},
                "read_capability": {"type": "string"},
                "external_read_contract": {"type": "object", "additionalProperties": True},
                "external": {"type": "object", "additionalProperties": {"type": "object", "additionalProperties": True}},
                "internal": {"type": "object", "additionalProperties": {"type": "object", "additionalProperties": True}},
            },
        },
        "Pagination": {
            "type": "object",
            "required": ["page", "page_size", "total_count", "total_pages"],
            "properties": {
                "page": {"type": "integer"},
                "page_size": {"type": "integer"},
                "total_count": {"type": "integer"},
                "total_pages": {"type": "integer"},
            },
        },
        "MessagesData": {
            "type": "object",
            "required": ["emails", "count", "has_more"],
            "properties": {
                "emails": {"type": "array", "items": {"$ref": "#/components/schemas/MessageSummary"}},
                "count": {"type": "integer"},
                "has_more": {"type": "boolean"},
            },
        },
        "MessageSummary": {
            "type": "object",
            "required": ["id", "email_address", "from_address", "subject", "timestamp", "created_at", "is_read", "method"],
            "properties": {
                "id": {"type": "string"},
                "email_address": {"type": "string"},
                "from_address": {"type": "string"},
                "subject": {"type": "string"},
                "content_preview": {"type": "string"},
                "has_html": {"type": "boolean"},
                "timestamp": {"type": "integer"},
                "created_at": {"type": "string"},
                "is_read": {"type": "boolean"},
                "method": {"type": "string"},
            },
        },
        "MessageDetail": {
            "type": "object",
            "required": [
                "id",
                "email_address",
                "from_address",
                "to_address",
                "subject",
                "content",
                "html_content",
                "raw_content",
                "timestamp",
                "created_at",
                "has_html",
                "method",
            ],
            "properties": {
                "id": {"type": "string"},
                "email_address": {"type": "string"},
                "from_address": {"type": "string"},
                "to_address": {"type": "string"},
                "subject": {"type": "string"},
                "content": {"type": "string"},
                "html_content": {"type": "string"},
                "raw_content": {"type": "string"},
                "timestamp": {"type": "integer"},
                "created_at": {"type": "string"},
                "has_html": {"type": "boolean"},
                "method": {"type": "string"},
                "content_preview": {"type": "string"},
                "is_read": {"type": "boolean"},
            },
            "additionalProperties": True,
        },
        "RawMessageData": {
            "type": "object",
            "required": ["id", "email_address", "raw_content", "method"],
            "properties": {
                "id": {"type": "string"},
                "email_address": {"type": "string"},
                "raw_content": {"type": "string"},
                "method": {"type": "string"},
            },
            "additionalProperties": False,
        },
        "VerificationResult": {
            "type": "object",
            "required": [
                "formatted",
                "verification_code",
                "verification_link",
                "confidence",
                "code_confidence",
                "link_confidence",
                "matched_email_id",
                "method",
                "folder",
                "channel",
            ],
            "properties": {
                "formatted": {"type": ["string", "null"]},
                "verification_code": {"type": ["string", "null"]},
                "verification_link": {"type": ["string", "null"]},
                "confidence": {"type": "string"},
                "code_confidence": {"type": "string"},
                "link_confidence": {"type": "string"},
                "matched_email_id": {"type": "string"},
                "method": {"type": "string"},
                "folder": {"type": "string"},
                "channel": {"type": "string"},
                "matched_subject": {"type": "string"},
                "matched_from": {"type": "string"},
                "used_ai": {"type": "boolean"},
            },
            "additionalProperties": True,
        },
        "AccountStatusData": {
            "type": "object",
            "required": [
                "email",
                "exists",
                "can_read",
                "account_type",
                "provider",
                "status",
                "preferred_method",
                "upstream_probe_ok",
                "probe_method",
                "last_probe_at",
                "last_probe_error",
                "last_refresh_at",
            ],
            "properties": {
                "email": {"type": "string"},
                "exists": {"type": "boolean"},
                "can_read": {"type": "boolean"},
                "account_type": {"type": "string"},
                "provider": {"type": "string"},
                "status": {"type": "string"},
                "preferred_method": {"type": "string"},
                "upstream_probe_ok": {"type": ["boolean", "null"]},
                "probe_method": {"type": "string"},
                "last_probe_at": {"type": "string"},
                "last_probe_error": {"type": "string"},
                "last_refresh_at": {"type": "string"},
                "group": {"type": "object", "additionalProperties": True},
            },
            "additionalProperties": True,
        },
        "ProbeStatusData": {
            "type": "object",
            "required": ["probe_id", "status", "email", "result", "error_code", "error_message", "created_at", "updated_at"],
            "properties": {
                "probe_id": {"type": "string"},
                "status": {"type": "string"},
                "email": {"type": "string"},
                "result": {"type": ["object", "null"], "additionalProperties": True},
                "error_code": {"type": ["string", "null"]},
                "error_message": {"type": ["string", "null"]},
                "created_at": {"type": "string"},
                "updated_at": {"type": "string"},
                "timeout_seconds": {"type": "integer"},
                "poll_interval": {"type": "integer"},
            },
            "additionalProperties": True,
        },
        "ProbeCreateData": {
            "type": "object",
            "required": ["probe_id", "status", "expires_at", "poll_url", "baseline_timestamp"],
            "properties": {
                "probe_id": {"type": "string"},
                "status": {"type": "string", "enum": ["pending"]},
                "expires_at": {"type": "string"},
                "poll_url": {"type": "string"},
                "baseline_timestamp": {"type": "integer"},
            },
            "additionalProperties": True,
        },
        "MailboxSessionData": {
            "type": "object",
            "required": [
                "session_type",
                "email",
                "provider",
                "provider_label",
                "read_capability",
                "created_at",
                "lifecycle",
                "external_mailbox_read_contract",
                "next_actions",
            ],
            "properties": {
                "session_type": {"type": "string", "enum": ["pool_claim", "task_temp_mailbox"]},
                "email": {"type": "string"},
                "provider": {"type": "string"},
                "provider_label": {"type": "string"},
                "read_capability": {"type": "string"},
                "created_at": {"type": "string"},
                "lifecycle": {"$ref": "#/components/schemas/MailboxSessionLifecycle"},
                "external_mailbox_read_contract": {"type": "object", "additionalProperties": True},
                "next_actions": {"type": "object", "additionalProperties": {"type": "object", "additionalProperties": True}},
            },
            "additionalProperties": False,
        },
        "MailboxSessionLifecycle": {
            "type": "object",
            "required": ["type"],
            "properties": {
                "type": {"type": "string", "enum": ["pool_claim", "task_temp_mailbox"]},
                "account_id": {"type": ["integer", "null"]},
                "claim_token": {"type": "string"},
                "claimed_at": {"type": "string"},
                "lease_expires_at": {"type": "string"},
                "complete_endpoint": {"type": "string", "example": f"{EXTERNAL_API_V1_PREFIX}/pool/claim-complete"},
                "release_endpoint": {"type": "string", "example": f"{EXTERNAL_API_V1_PREFIX}/pool/claim-release"},
                "task_token": {"type": "string"},
                "finish_endpoint": {"type": "string", "example": f"{EXTERNAL_API_V1_PREFIX}/temp-emails/{{task_token}}/finish"},
                "visible_in_ui": {"type": "boolean"},
                "status": {"type": "string"},
            },
            "additionalProperties": False,
        },
        "MailboxSessionCloseData": {
            "type": "object",
            "required": ["session_type", "close_action", "status"],
            "properties": {
                "session_type": {"type": "string", "enum": ["pool_claim", "task_temp_mailbox"]},
                "close_action": {"type": "string", "enum": ["complete_claim", "release_claim", "finish_task_mailbox"]},
                "status": {"type": "string", "enum": ["closed"]},
                "account_id": {"type": ["integer", "null"]},
                "pool_status": {"type": ["string", "null"]},
                "task_token": {"type": ["string", "null"]},
                "email": {"type": ["string", "null"]},
            },
            "additionalProperties": False,
        },
        "MailboxSessionReadData": {
            "type": "object",
            "required": ["session_type", "read_action", "email", "status", "result"],
            "properties": {
                "session_type": {"type": "string", "enum": ["pool_claim", "task_temp_mailbox"]},
                "read_action": {
                    "type": "string",
                    "enum": ["messages", "latest_message", "message_detail", "message_raw", "verification_code", "verification_link", "wait_message"],
                },
                "email": {"type": "string"},
                "status": {"type": "string", "enum": ["ok", "pending"]},
                "result": {
                    "oneOf": [
                        {"$ref": "#/components/schemas/MessagesData"},
                        {"$ref": "#/components/schemas/MessageSummary"},
                        {"$ref": "#/components/schemas/MessageDetail"},
                        {"$ref": "#/components/schemas/RawMessageData"},
                        {"$ref": "#/components/schemas/VerificationResult"},
                        {"$ref": "#/components/schemas/ProbeCreateData"},
                        {"$ref": "#/components/schemas/ProbeStatusData"},
                    ]
                },
            },
            "additionalProperties": False,
        },
        "PoolClaimData": {"type": "object", "additionalProperties": True},
        "PoolLifecycleData": {"type": "object", "additionalProperties": True},
        "PoolStatsData": {"type": "object", "additionalProperties": True},
        "TaskTempMailboxData": {"type": "object", "additionalProperties": True},
        "PoolReleaseRequest": {
            "type": "object",
            "required": ["account_id", "claim_token", "caller_id", "task_id"],
            "additionalProperties": False,
            "properties": {
                "account_id": {"type": "integer"},
                "claim_token": {"type": "string", "minLength": 1},
                "caller_id": {"type": "string", "minLength": 1, "maxLength": CALLER_ID_MAX_LEN},
                "task_id": {"type": "string", "minLength": 1, "maxLength": TASK_ID_MAX_LEN},
                "reason": {"type": ["string", "null"], "maxLength": REASON_MAX_LEN},
            },
        },
        "PoolCompleteRequest": {
            "type": "object",
            "required": ["account_id", "claim_token", "caller_id", "task_id", "result"],
            "additionalProperties": False,
            "properties": {
                "account_id": {"type": "integer"},
                "claim_token": {"type": "string", "minLength": 1},
                "caller_id": {"type": "string", "minLength": 1, "maxLength": CALLER_ID_MAX_LEN},
                "task_id": {"type": "string", "minLength": 1, "maxLength": TASK_ID_MAX_LEN},
                "result": {"type": "string", "enum": sorted(VALID_RESULTS)},
                "detail": {"type": ["string", "null"], "maxLength": DETAIL_MAX_LEN},
            },
        },
        "PoolClaimRequest": {
            "type": "object",
            "required": ["caller_id", "task_id"],
            "additionalProperties": False,
            "properties": {
                "caller_id": {"type": "string", "minLength": 1, "maxLength": CALLER_ID_MAX_LEN},
                "task_id": {"type": "string", "minLength": 1, "maxLength": TASK_ID_MAX_LEN},
                "provider": _nullable_string_enum_schema(
                    list(pool_claim_scope.get("allowed_values") or []),
                    description=(
                        "Optional mailbox provider selector. Omit it to use the pool default; pass null or auto "
                        "for automatic selection. Values come from selection_policy.scopes.explicit_pool_claim.allowed_values."
                    ),
                ),
                "email_domain": {"type": ["string", "null"], "maxLength": EMAIL_DOMAIN_MAX_LEN},
                "project_key": {"type": ["string", "null"], "maxLength": PROJECT_KEY_MAX_LEN},
            },
        },
        "PoolLifecycleRequest": {
            "oneOf": [
                {"$ref": "#/components/schemas/PoolReleaseRequest"},
                {"$ref": "#/components/schemas/PoolCompleteRequest"},
            ],
        },
        "TaskTempMailboxApplyRequest": {
            "type": "object",
            "required": ["caller_id", "task_id"],
            "additionalProperties": False,
            "properties": {
                "caller_id": {"type": "string", "minLength": 1, "maxLength": CALLER_ID_MAX_LEN},
                "task_id": {"type": "string", "minLength": 1, "maxLength": TASK_ID_MAX_LEN},
                "prefix": {
                    "type": ["string", "null"],
                    "maxLength": TASK_MAILBOX_PREFIX_MAX_LEN,
                    "description": "Platform maximum. Provider-specific prefix rules remain discoverable from the temp-mail options endpoint.",
                },
                "domain": {"type": ["string", "null"], "maxLength": EMAIL_DOMAIN_MAX_LEN},
                "provider_name": _nullable_string_enum_schema(
                    list(task_temp_apply_scope.get("allowed_values") or []),
                    description=(
                        "Optional temp-mail provider selector. Values come from "
                        "selection_policy.scopes.task_temp_apply.allowed_values."
                    ),
                ),
            },
        },
        "MailboxSessionStartRequest": {
            "type": "object",
            "required": ["caller_id", "task_id"],
            "additionalProperties": False,
            "properties": {
                "caller_id": {"type": "string", "minLength": 1, "maxLength": CALLER_ID_MAX_LEN},
                "task_id": {"type": "string", "minLength": 1, "maxLength": TASK_ID_MAX_LEN},
                "source_strategy": {
                    "type": "string",
                    "enum": ["pool_first", "task_temp_first", "pool_only", "task_temp_only"],
                    "default": "pool_first",
                },
                "provider": _nullable_string_enum_schema(
                    list(pool_claim_scope.get("allowed_values") or []),
                    description="Optional pool provider selector used by pool-backed session strategies.",
                ),
                "provider_name": _nullable_string_enum_schema(
                    list(task_temp_apply_scope.get("allowed_values") or []),
                    description="Optional task temp-mail provider selector used by task-temp-backed session strategies.",
                ),
                "email_domain": {"type": ["string", "null"], "maxLength": EMAIL_DOMAIN_MAX_LEN},
                "project_key": {"type": ["string", "null"], "maxLength": PROJECT_KEY_MAX_LEN},
                "prefix": {"type": ["string", "null"], "maxLength": TASK_MAILBOX_PREFIX_MAX_LEN},
                "domain": {"type": ["string", "null"], "maxLength": EMAIL_DOMAIN_MAX_LEN},
            },
        },
        "MailboxSessionCloseRequest": {
            "type": "object",
            "required": ["session_type", "caller_id", "task_id"],
            "additionalProperties": False,
            "properties": {
                "session_type": {"type": "string", "enum": ["pool_claim", "task_temp_mailbox"]},
                "account_id": {"type": ["integer", "null"]},
                "claim_token": {"type": ["string", "null"]},
                "task_token": {"type": ["string", "null"]},
                "caller_id": {"type": "string", "minLength": 1, "maxLength": CALLER_ID_MAX_LEN},
                "task_id": {"type": "string", "minLength": 1, "maxLength": TASK_ID_MAX_LEN},
                "result": {
                    "type": ["string", "null"],
                    "maxLength": DETAIL_MAX_LEN,
                    "description": "For pool_claim, release releases the claim and other valid pool result values complete it. For task_temp_mailbox, this is an optional audit label.",
                },
                "detail": {"type": ["string", "null"], "maxLength": DETAIL_MAX_LEN},
                "reason": {"type": ["string", "null"], "maxLength": REASON_MAX_LEN},
            },
        },
        "MailboxSessionReadRequest": {
            "type": "object",
            "required": ["session_type", "read_action", "caller_id", "task_id"],
            "additionalProperties": False,
            "properties": {
                "session_type": {"type": "string", "enum": ["pool_claim", "task_temp_mailbox"]},
                "read_action": {
                    "type": "string",
                    "enum": ["messages", "latest_message", "message_detail", "message_raw", "verification_code", "verification_link", "wait_message"],
                },
                "caller_id": {"type": "string", "minLength": 1, "maxLength": CALLER_ID_MAX_LEN},
                "task_id": {"type": "string", "minLength": 1, "maxLength": TASK_ID_MAX_LEN},
                "email": {"type": ["string", "null"]},
                "claim_token": {"type": ["string", "null"], "description": "Required for pool_claim session reads."},
                "task_token": {"type": ["string", "null"], "description": "Required for task_temp_mailbox session reads."},
                "message_id": {"type": ["string", "null"]},
                "folder": {"type": ["string", "null"], "enum": [None, "inbox", "junkemail", "deleteditems"]},
                "skip": {"type": ["integer", "null"], "minimum": 0},
                "top": {"type": ["integer", "null"], "minimum": 1, "maximum": 50},
                "from_contains": {"type": ["string", "null"]},
                "subject_contains": {"type": ["string", "null"]},
                "since_minutes": {"type": ["integer", "null"], "minimum": 1},
                "code_length": {"type": ["string", "null"]},
                "code_regex": {"type": ["string", "null"]},
                "code_source": {"type": ["string", "null"], "enum": [None, "subject", "content", "html", "all"]},
                "timeout_seconds": {"type": ["integer", "null"], "minimum": 1, "maximum": 120},
                "poll_interval": {"type": ["integer", "null"], "minimum": 1, "maximum": 120},
                "mode": {"type": ["string", "null"], "enum": [None, "sync", "async"]},
            },
        },
        "TaskTempMailboxFinishRequest": {
            "type": "object",
            "additionalProperties": False,
            "properties": {
                "result": {
                    "type": ["string", "null"],
                    "maxLength": DETAIL_MAX_LEN,
                    "description": "Optional audit label only; finishing the task mailbox always marks it finished.",
                },
                "detail": {"type": ["string", "null"], "maxLength": DETAIL_MAX_LEN},
            },
        },
    }
