#!/usr/bin/env python3
"""Concatenate classic frontend scripts into one production bundle.

Keeps development multi-file layout; production (Docker) serves a single
static/js/bundles/app.js to cut HTTP request storms that make navigation feel laggy.
"""
from __future__ import annotations

import re
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
SCRIPTS_HTML = ROOT / "templates" / "partials" / "scripts.html"
OUT_DIR = ROOT / "static" / "js" / "bundles"
OUT_FILE = OUT_DIR / "app.js"
MARKER_START = "filename='js/"
MARKER_END = "'"


def script_paths_from_html() -> list[Path]:
    text = SCRIPTS_HTML.read_text(encoding="utf-8")
    paths: list[Path] = []
    for match in re.finditer(r"filename='(js/[^']+)'", text):
        rel = match.group(1)
        path = ROOT / "static" / rel
        if not path.is_file():
            raise FileNotFoundError(path)
        paths.append(path)
    if not paths:
        raise RuntimeError("no script paths found in scripts.html")
    return paths


def build() -> Path:
    paths = script_paths_from_html()
    parts: list[str] = [
        "/* MailOps frontend bundle — generated by scripts/build_frontend_bundle.py */\n",
        f"/* sources: {len(paths)} files */\n",
    ]
    for path in paths:
        rel = path.relative_to(ROOT / "static").as_posix()
        body = path.read_text(encoding="utf-8")
        parts.append(f"\n/* ===== {rel} ===== */\n")
        parts.append(body)
        if not body.endswith("\n"):
            parts.append("\n")
    OUT_DIR.mkdir(parents=True, exist_ok=True)
    OUT_FILE.write_text("".join(parts), encoding="utf-8")
    return OUT_FILE


def main() -> None:
    out = build()
    size = out.stat().st_size
    print(f"wrote {out.relative_to(ROOT)} ({size} bytes)")


if __name__ == "__main__":
    main()
